# Generated by Django 4.2.8 on 2024-03-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studenthandler', '0001_initial'),
        ('teacherhandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotClassRoom',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255)),
                ('class_avatar', models.CharField(default='duck', max_length=100)),
                ('students', models.ManyToManyField(blank=True, related_name='classrooms', to='studenthandler.studentuser')),
                ('teacher', models.ManyToManyField(blank=True, related_name='classrooms', to='teacherhandler.teacheruser')),
            ],
        ),
    ]
