# Generated by Django 4.2.8 on 2024-03-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomhandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.IntegerField()),
                ('message_content', models.CharField(max_length=2000)),
                ('message_type', models.CharField(max_length=20)),
                ('message_avatar', models.CharField(max_length=50)),
            ],
        ),
    ]
