# Generated by Django 4.2.8 on 2024-03-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomhandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotclassroom',
            name='class_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
