# Generated by Django 4.2.8 on 2024-03-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomhandler', '0002_classroommessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroommessage',
            old_name='message_type',
            new_name='user_type',
        ),
        migrations.AddField(
            model_name='classroommessage',
            name='user_name',
            field=models.CharField(default='li', max_length=100),
        ),
    ]
