# Generated by Django 4.2.8 on 2024-03-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratorhandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeicyModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('learningRate', models.FloatField(default=0.0213)),
                ('batchSize', models.IntegerField(default=64)),
                ('epoches', models.IntegerField(default=85)),
                ('hiddenLayerSize', models.IntegerField(default=256)),
                ('vocabularySize', models.BigIntegerField(default=100000)),
                ('maxSeqLength', models.IntegerField(default=500)),
                ('dropoutRate', models.FloatField(default=0.32)),
                ('gradientClippingThreshold', models.FloatField(default=3.26)),
                ('optimizer', models.CharField(default='adam', max_length=100)),
                ('lossFunction', models.CharField(default='meanSquaredError', max_length=100)),
            ],
        ),
    ]
