# Generated by Django 4.2.8 on 2024-02-01 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login_time', models.DateTimeField(default=django.utils.timezone.now, max_length=30)),
                ('in_class', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
